//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Additional_operation__load_unload_
    {
        public int Id { get; set; }
        public int Additional_Operation_ID { get; set; }
        public int Load_and_Unload_operation_ID { get; set; }
    
        public virtual Additional_Operation Additional_Operation { get; set; }
        public virtual Loading_and_unloading_operation Loading_and_unloading_operations { get; set; }
    }
}
