//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Additional_operation__load_unload_
    {
        public int Id { get; set; }
        public int Additional_Operation_ID { get; set; }
        public int Load_and_Unload_operation_ID { get; set; }
    
        public virtual Additional_Operation Additional_Operation { get; set; }
        public virtual Loading_and_unloading_operation Loading_and_unloading_operations { get; set; }
    }
}
