//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Tralers_in_WayList
    {
        public int Id { get; set; }
        public int Car_Trailer_ID { get; set; }
        public int WayList_ID { get; set; }
    
        public virtual Car_Trailer Car_Trailer { get; set; }
        public virtual WayList WayList { get; set; }
    }
}
