//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.WayBills_In_Contract = new HashSet<WayBills_In_Contract>();
            this.WayLists = new HashSet<WayList>();
        }
    
        public int Id { get; set; }
        public string Company { get; set; }
        public int Legal_entity_ID { get; set; }
        public System.TimeSpan Arrive_time { get; set; }
        public string Where_to_get_cargo { get; set; }
        public string Where_to_deliver_cargo { get; set; }
        public int Cargo_ID { get; set; }
        public int Count_trips { get; set; }
        public double Distance { get; set; }
        public double Tonnes { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Legal_Entity Legal_Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WayBills_In_Contract> WayBills_In_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WayList> WayLists { get; set; }
    }
}
