//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Costing()
        {
            this.WayBills = new HashSet<WayBill>();
        }
    
        public int Id { get; set; }
        public string Costing_kind { get; set; }
        public double For_tonnes { get; set; }
        public double Underweight { get; set; }
        public double For_spec__prnsp { get; set; }
        public double For_transport_service { get; set; }
        public double Load_unload_work { get; set; }
        public double Over_standard_simple_loading { get; set; }
        public double Over_standard_simple_unloading { get; set; }
        public double Other_costing { get; set; }
        public double Discounts_for_reducing_downtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WayBill> WayBills { get; set; }
    }
}
