//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance_of_transportation_by_road_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Distance_of_transportation_by_road_group()
        {
            this.Other_Information = new HashSet<Other_Information>();
        }
    
        public int Id { get; set; }
        public double Total { get; set; }
        public double In_city { get; set; }
        public double First_group { get; set; }
        public double Second_group { get; set; }
        public double Third_group { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Other_Information> Other_Information { get; set; }
    }
}
