//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver_Accompanying_in_WayList
    {
        public int Id { get; set; }
        public int Driver_Accompanying_ID { get; set; }
        public int WayList_ID { get; set; }
    
        public virtual Driver_Accompanying Driver_Accompanying { get; set; }
        public virtual WayList WayList { get; set; }
    }
}
