//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver_Work
    {
        public int Id { get; set; }
        public int Operation_ID { get; set; }
        public System.TimeSpan Time_on_shedule { get; set; }
        public double Zero_mileage { get; set; }
        public double Speedometer_display { get; set; }
        public System.TimeSpan Fact_time { get; set; }
        public int Moving_Fuel_ID { get; set; }
        public int Way_List_ID { get; set; }
    
        public virtual Moving_Fuel Moving_Fuel { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual WayList WayList { get; set; }
    }
}
