//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information_about_the_cargo
    {
        public int Id { get; set; }
        public string Nomenclature_code { get; set; }
        public string Preisc__position { get; set; }
        public int Cargo_ID { get; set; }
        public int Count { get; set; }
        public double Price { get; set; }
        public double Summary { get; set; }
        public int Documents_count { get; set; }
        public string Pack_kind { get; set; }
        public int Place_Count { get; set; }
        public string Mass_determination_method { get; set; }
        public double Mass { get; set; }
        public int Waybill_ID { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual WayBill WayBill { get; set; }
    }
}
