//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moving_Fuel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moving_Fuel()
        {
            this.Driver_Work = new HashSet<Driver_Work>();
        }
    
        public int Id { get; set; }
        public int Fuel_ID { get; set; }
        public double Given { get; set; }
        public double Balance_at_checkout { get; set; }
        public double Balance_at_checkin { get; set; }
        public double Commissioned { get; set; }
        public double Coefficient_of_change_in_the_norm { get; set; }
        public int Work_Time_SpecObor_ { get; set; }
        public int Work_Time_DvigFe_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver_Work> Driver_Work { get; set; }
        public virtual Fuel Fuel { get; set; }
    }
}
