//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WayBills_In_Contract
    {
        public int Id { get; set; }
        public int Waybill_ID { get; set; }
        public int Contract_ID { get; set; }
        public System.TimeSpan Arrive_time { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual WayBill WayBill { get; set; }
    }
}
