//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAutoSupplying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaysAndShipping
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EndStation { get; set; }
        public double Distance { get; set; }
        public System.TimeSpan Time_Loop { get; set; }
        public int Shipping_Kind { get; set; }
    
        public virtual ShippingKind ShippingKind { get; set; }
    }
}
